"""One-off data assessment: inventory every table/column in the sandbox and
sample a few rows, writing the result to docs/data_dictionary.md.

Run once, by hand, before designing the agent's query tools:
    python scripts/explore_data.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.snowflake_client import run_query  # noqa: E402

SCHEMAS = ["CRM", "PRODUCT", "SUPPORT"]
SAMPLE_ROWS = 5


def list_tables(schema: str) -> list[str]:
    rows = run_query(f"SHOW TABLES IN SCHEMA PERSONIO.{schema}")
    return [row["name"] for row in rows]


def describe_table(schema: str, table: str) -> list[dict]:
    return run_query(f"DESCRIBE TABLE PERSONIO.{schema}.{table}")


def sample_table(schema: str, table: str, limit: int = SAMPLE_ROWS) -> list[dict]:
    return run_query(f"SELECT * FROM PERSONIO.{schema}.{table} LIMIT {limit}")


def row_count(schema: str, table: str) -> int:
    rows = run_query(f"SELECT COUNT(*) AS row_count FROM PERSONIO.{schema}.{table}")
    return rows[0]["ROW_COUNT"]


def main() -> None:
    lines = ["# Data dictionary — PERSONIO sandbox\n"]
    lines.append("Auto-generated by `scripts/explore_data.py`.\n")

    for schema in SCHEMAS:
        lines.append(f"\n## Schema: {schema}\n")
        try:
            tables = list_tables(schema)
        except Exception as exc:  # schema may not exist / no access
            lines.append(f"_Could not list tables: {exc}_\n")
            continue

        for table in tables:
            lines.append(f"\n### {schema}.{table}\n")
            try:
                n = row_count(schema, table)
                lines.append(f"Row count: {n}\n")
            except Exception as exc:
                lines.append(f"_Could not count rows: {exc}_\n")

            try:
                cols = describe_table(schema, table)
                lines.append("\n| column | type |\n|---|---|")
                for col in cols:
                    lines.append(f"| {col['name']} | {col['type']} |")
                lines.append("")
            except Exception as exc:
                lines.append(f"_Could not describe table: {exc}_\n")

            try:
                sample = sample_table(schema, table)
                lines.append("\nSample rows:\n")
                lines.append("```")
                for row in sample:
                    lines.append(str(row))
                lines.append("```")
            except Exception as exc:
                lines.append(f"_Could not sample rows: {exc}_\n")

    out_path = Path(__file__).resolve().parent.parent / "docs" / "data_dictionary.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
